/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tptranspart2.vistas;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author julie
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
         Toolkit miPantalla= Toolkit.getDefaultToolkit();//Asi obtengo la pantalla
       Dimension tamanioPantalla=miPantalla.getScreenSize();//obtengo  la resolución de mi pantalla
       int alturaPantalla=tamanioPantalla.height+200;
       int anchoPantalla=tamanioPantalla.width;
       setSize(anchoPantalla/2,alturaPantalla/2);
       setLocation(anchoPantalla/4,alturaPantalla/4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MISalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MIFormMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MIFormAlumno = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MIManejoInscripciones = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MIManipulacionNotas = new javax.swing.JMenuItem();
        MIListadoAlumnoPorMateria = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 697, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        MISalir.setText("Salir");
        jMenu1.add(MISalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materias");

        MIFormMateria.setText("Formulario de materia");
        MIFormMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIFormMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(MIFormMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Alumnos");

        MIFormAlumno.setText("Formulario de alumno");
        MIFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIFormAlumnoActionPerformed(evt);
            }
        });
        jMenu3.add(MIFormAlumno);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Inscripciones");

        MIManejoInscripciones.setText("Manejo de inscripciones");
        MIManejoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIManejoInscripcionesActionPerformed(evt);
            }
        });
        jMenu4.add(MIManejoInscripciones);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Carga de notas");

        MIManipulacionNotas.setText("Manipulacion de notas");
        MIManipulacionNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIManipulacionNotasActionPerformed(evt);
            }
        });
        jMenu5.add(MIManipulacionNotas);

        jMenuBar1.add(jMenu5);

        MIListadoAlumnoPorMateria.setText("Consultas");

        jMenuItem6.setText("Listado de alumnos por materia");
        MIListadoAlumnoPorMateria.add(jMenuItem6);

        jMenuBar1.add(MIListadoAlumnoPorMateria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    
    
    private void MIFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIFormAlumnoActionPerformed
        escritorio.removeAll(); //si hay una ventana abierta, la limpia,la remueve 
        escritorio.repaint();//dibuja todo de nuevo
        AlumnosView alumnosView=new AlumnosView();
        alumnosView.setVisible(true);
        escritorio.add(alumnosView);
        escritorio.moveToFront(alumnosView);
        
    }//GEN-LAST:event_MIFormAlumnoActionPerformed

    private void MIFormMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIFormMateriaActionPerformed
        escritorio.removeAll(); //si hay una ventana abierta, la limpia,la remueve 
        escritorio.repaint();//dibuja todo de nuevo
        MateriasView materiasView=new MateriasView();
        materiasView.setVisible(true);
        escritorio.add(materiasView);
        escritorio.moveToFront(materiasView);
    }//GEN-LAST:event_MIFormMateriaActionPerformed

    private void MIManejoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIManejoInscripcionesActionPerformed
        escritorio.removeAll(); //si hay una ventana abierta, la limpia,la remueve 
        escritorio.repaint();//dibuja todo de nuevo
        ManejoInscripcionesView manejoInscripcionesView=new ManejoInscripcionesView();
        manejoInscripcionesView.setVisible(true);
        escritorio.add( manejoInscripcionesView);
        escritorio.moveToFront(manejoInscripcionesView);
    }//GEN-LAST:event_MIManejoInscripcionesActionPerformed

    private void MIManipulacionNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIManipulacionNotasActionPerformed
        escritorio.removeAll(); //si hay una ventana abierta, la limpia,la remueve 
        escritorio.repaint();//dibuja todo de nuevo
        ManipulacionDeNotasView manipulacionDeNotasView=new ManipulacionDeNotasView();
        manipulacionDeNotasView.setVisible(true);
        escritorio.add( manipulacionDeNotasView);
        escritorio.moveToFront(manipulacionDeNotasView);
    }//GEN-LAST:event_MIManipulacionNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIFormAlumno;
    private javax.swing.JMenuItem MIFormMateria;
    private javax.swing.JMenu MIListadoAlumnoPorMateria;
    private javax.swing.JMenuItem MIManejoInscripciones;
    private javax.swing.JMenuItem MIManipulacionNotas;
    private javax.swing.JMenuItem MISalir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    // End of variables declaration//GEN-END:variables
}
